In [3]:
import pycaret.classification as pycc
import pickle
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
list_col_exc =["PassengerId", "Ticket"] + ["Name"]

In [15]:
list_col_exc

['PassengerId', 'Ticket', 'Name']

In [16]:
pycc.setup(df, target = "Survived", train_size=0.75, silent = True, use_gpu = True, ignore_features=(list_col_exc))

(10,
 <MLUsecase.CLASSIFICATION: 1>,
 None,
 {'lr': <pycaret.containers.models.classification.LogisticRegressionClassifierContainer at 0x1c186b343d0>,
  'knn': <pycaret.containers.models.classification.KNeighborsClassifierContainer at 0x1c186b345b0>,
  'nb': <pycaret.containers.models.classification.GaussianNBClassifierContainer at 0x1c186b34610>,
  'dt': <pycaret.containers.models.classification.DecisionTreeClassifierContainer at 0x1c186b34820>,
  'svm': <pycaret.containers.models.classification.SGDClassifierContainer at 0x1c186b34850>,
  'rbfsvm': <pycaret.containers.models.classification.SVCClassifierContainer at 0x1c186b34e50>,
  'gpc': <pycaret.containers.models.classification.GaussianProcessClassifierContainer at 0x1c186b34fd0>,
  'mlp': <pycaret.containers.models.classification.MLPClassifierContainer at 0x1c1871b50d0>,
  'ridge': <pycaret.containers.models.classification.RidgeClassifierContainer at 0x1c1871b5370>,
  'rf': <pycaret.containers.models.classification.RandomForestClassifierContainer at 0x1c1871b5520>,
  'qda': <pycaret.containers.models.classification.QuadraticDiscriminantAnalysisContainer at 0x1c1871b5640>,
  'ada': <pycaret.containers.models.classification.AdaBoostClassifierContainer at 0x1c1871b5af0>,
  'gbc': <pycaret.containers.models.classification.GradientBoostingClassifierContainer at 0x1c1871b5c70>,
  'lda': <pycaret.containers.models.classification.LinearDiscriminantAnalysisContainer at 0x1c1871b5cd0>,
  'et': <pycaret.containers.models.classification.ExtraTreesClassifierContainer at 0x1c1871b9190>,
  'lightgbm': <pycaret.containers.models.classification.LGBMClassifierContainer at 0x1c1871b9730>,
  'dummy': <pycaret.containers.models.classification.DummyClassifierContainer at 0x1c1871b9c10>,
  'Bagging': <pycaret.containers.models.classification.BaggingClassifierContainer at 0x1c1871b91f0>,
  'Stacking': <pycaret.containers.models.classification.StackingClassifierContainer at 0x1c1871b9ca0>,
  'Voting': <pycaret.containers.models.classification.VotingClassifierContainer at 0x1c1871b9d60>,
  'CalibratedCV': <pycaret.containers.models.classification.CalibratedClassifierCVContainer at 0x1c1871b9df0>},
            Age       Fare  Pclass_1  Pclass_2  Pclass_3  Sex_male  SibSp_0  \
 0    22.000000   7.250000       0.0       0.0       1.0       1.0      0.0
 1    38.000000  71.283302       1.0       0.0       0.0       0.0      0.0
 2    26.000000   7.925000       0.0       0.0       1.0       0.0      1.0
 3    35.000000  53.099998       1.0       0.0       0.0       0.0      0.0
 4    35.000000   8.050000       0.0       0.0       1.0       1.0      1.0
 ..         ...        ...       ...       ...       ...       ...      ...
 886  27.000000  13.000000       0.0       1.0       0.0       1.0      1.0
 887  19.000000  30.000000       1.0       0.0       0.0       0.0      1.0
 888  29.496336  23.450001       0.0       0.0       1.0       0.0      0.0
 889  26.000000  30.000000       1.0       0.0       0.0       1.0      1.0
 890  32.000000   7.750000       0.0       0.0       1.0       1.0      1.0

      SibSp_1  SibSp_2  SibSp_3  ...  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  \
 0        1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 1        1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 2        0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 3        1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 4        0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 ..       ...      ...      ...  ...        ...        ...       ...       ...
 886      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 887      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 888      1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 889      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 890      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0

      Cabin_T  Cabin_not_available  Embarked_C  Embarked_Q  Embarked_S  \
 0        0.0                  1.0         0.0         0.0         1.0
 1        0.0                  0.0         1.0         0.0         0.0
 2        0.0                  1.0         0.0         0.0         1.0
 3        0.0                  0.0         0.0         0.0         1.0
 4        0.0                  1.0         0.0         0.0         1.0
 ..       ...                  ...         ...         ...         ...
 886      0.0                  1.0         0.0         0.0         1.0
 887      0.0                  0.0         0.0         0.0         1.0
 888      0.0                  1.0         0.0         0.0         1.0
 889      0.0                  0.0         1.0         0.0         0.0
 890      0.0                  1.0         0.0         1.0         0.0

      Embarked_not_available
 0                       0.0
 1                       0.0
 2                       0.0
 3                       0.0
 4                       0.0
 ..                      ...
 886                     0.0
 887                     0.0
 888                     0.0
 889                     0.0
 890                     0.0

 [891 rows x 132 columns],
 Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False),
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: Survived, Length: 891, dtype: int64,
 Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=False,
                                       features_todrop=['PassengerId', 'Ticket',
                                                        'Name'],
                                       id_columns=['PassengerId'],
                                       ml_usecase='classification',
                                       numerical_features=[], target='Survived',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical...
                 ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                 ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                 ('cluster_all', 'passthrough'),
                 ('dummy', Dummify(target='Survived')),
                 ('fix_perfect', Remove_100(target='Survived')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough')],
          verbose=False),
 329    1
 745    0
 194    1
 76     0
 702    0
       ..
 239    0
 873    0
 247    1
 195    1
 441    0
 Name: Survived, Length: 668, dtype: int64,
 'Survived',
 1,
 {'acc': <pycaret.containers.metrics.classification.AccuracyMetricContainer at 0x1c1871b9e20>,
  'auc': <pycaret.containers.metrics.classification.ROCAUCMetricContainer at 0x1c1871b9e50>,
  'recall': <pycaret.containers.metrics.classification.RecallMetricContainer at 0x1c1871b9f40>,
  'precision': <pycaret.containers.metrics.classification.PrecisionMetricContainer at 0x1c186e720d0>,
  'f1': <pycaret.containers.metrics.classification.F1MetricContainer at 0x1c186e72220>,
  'kappa': <pycaret.containers.metrics.classification.KappaMetricContainer at 0x1c186e72370>,
  'mcc': <pycaret.containers.metrics.classification.MCCMetricContainer at 0x1c186e72400>},
 True,
 {'parameter': 'Hyperparameters',
  'auc': 'AUC',
  'confusion_matrix': 'Confusion Matrix',
  'threshold': 'Threshold',
  'pr': 'Precision Recall',
  'error': 'Prediction Error',
  'class_report': 'Class Report',
  'rfe': 'Feature Selection',
  'learning': 'Learning Curve',
  'manifold': 'Manifold Learning',
  'calibration': 'Calibration Curve',
  'vc': 'Validation Curve',
  'dimension': 'Dimensions',
  'feature': 'Feature Importance',
  'feature_all': 'Feature Importance (All)',
  'boundary': 'Decision Boundary',
  'lift': 'Lift Chart',
  'gain': 'Gain Chart',
  'tree': 'Decision Tree',
  'ks': 'KS Statistic Plot'},
 False,
            Age        Fare  Pclass_1  Pclass_2  Pclass_3  Sex_male  SibSp_0  \
 329  16.000000   57.979198       1.0       0.0       0.0       0.0      1.0
 745  70.000000   71.000000       1.0       0.0       0.0       1.0      0.0
 194  44.000000   27.720800       1.0       0.0       0.0       0.0      1.0
 76   29.496336    7.895800       0.0       0.0       1.0       1.0      1.0
 702  18.000000   14.454200       0.0       0.0       1.0       0.0      1.0
 ..         ...         ...       ...       ...       ...       ...      ...
 239  33.000000   12.275000       0.0       1.0       0.0       1.0      1.0
 873  47.000000    9.000000       0.0       0.0       1.0       1.0      1.0
 247  24.000000   14.500000       0.0       1.0       0.0       0.0      1.0
 195  58.000000  146.520798       1.0       0.0       0.0       0.0      1.0
 441  20.000000    9.500000       0.0       0.0       1.0       1.0      1.0

      SibSp_1  SibSp_2  SibSp_3  ...  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  \
 329      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 745      1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 194      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 76       0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 702      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 ..       ...      ...      ...  ...        ...        ...       ...       ...
 239      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 873      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 247      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 195      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 441      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0

      Cabin_T  Cabin_not_available  Embarked_C  Embarked_Q  Embarked_S  \
 329      0.0                  0.0         1.0         0.0         0.0
 745      0.0                  0.0         0.0         0.0         1.0
 194      0.0                  0.0         1.0         0.0         0.0
 76       0.0                  1.0         0.0         0.0         1.0
 702      0.0                  1.0         1.0         0.0         0.0
 ..       ...                  ...         ...         ...         ...
 239      0.0                  1.0         0.0         0.0         1.0
 873      0.0                  1.0         0.0         0.0         1.0
 247      0.0                  1.0         0.0         0.0         1.0
 195      0.0                  0.0         1.0         0.0         0.0
 441      0.0                  1.0         0.0         0.0         1.0

      Embarked_not_available
 329                     0.0
 745                     0.0
 194                     0.0
 76                      0.0
 702                     0.0
 ..                      ...
 239                     0.0
 873                     0.0
 247                     0.0
 195                     0.0
 441                     0.0

 [668 rows x 132 columns],
 False,
 None,
 'lightgbm',
      PassengerId  Survived  Pclass  \
 0              1         0       3
 1              2         1       1
 2              3         1       3
 3              4         1       1
 4              5         0       3
 ..           ...       ...     ...
 886          887         0       2
 887          888         1       1
 888          889         0       3
 889          890         1       1
 890          891         0       3

                                                   Name     Sex   Age  SibSp  \
 0                              Braund, Mr. Owen Harris    male  22.0      1
 1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
 2                               Heikkinen, Miss. Laina  female  26.0      0
 3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
 4                             Allen, Mr. William Henry    male  35.0      0
 ..                                                 ...     ...   ...    ...
 886                              Montvila, Rev. Juozas    male  27.0      0
 887                       Graham, Miss. Margaret Edith  female  19.0      0
 888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
 889                              Behr, Mr. Karl Howell    male  26.0      0
 890                                Dooley, Mr. Patrick    male  32.0      0

      Parch            Ticket     Fare Cabin Embarked
 0        0         A/5 21171   7.2500   NaN        S
 1        0          PC 17599  71.2833   C85        C
 2        0  STON/O2. 3101282   7.9250   NaN        S
 3        0            113803  53.1000  C123        S
 4        0            373450   8.0500   NaN        S
 ..     ...               ...      ...   ...      ...
 886      0            211536  13.0000   NaN        S
 887      0            112053  30.0000   B42        S
 888      2        W./C. 6607  23.4500   NaN        S
 889      0            111369  30.0000  C148        C
 890      0            370376   7.7500   NaN        Q

 [891 rows x 12 columns],
 -1,
 7196,
 'box-cox',
 False,
 [],
 [<pandas.io.formats.style.Styler at 0x1c186eb8460>],
 {'USI',
  'X',
  'X_test',
  'X_train',
  '_all_metrics',
  '_all_models',
  '_all_models_internal',
  '_available_plots',
  '_gpu_n_jobs_param',
  '_internal_pipeline',
  '_ml_usecase',
  'create_model_container',
  'dashboard_logger',
  'data_before_preprocess',
  'display_container',
  'exp_name_log',
  'experiment__',
  'fix_imbalance_method_param',
  'fix_imbalance_param',
  'fold_generator',
  'fold_groups_param',
  'fold_groups_param_full',
  'fold_param',
  'fold_shuffle_param',
  'gpu_param',
  'html_param',
  'imputation_classifier',
  'imputation_regressor',
  'iterative_imputation_iters_param',
  'log_plots_param',
  'logging_param',
  'master_model_container',
  'n_jobs_param',
  'prep_pipe',
  'pycaret_globals',
  'seed',
  'stratify_param',
  'target_param',
  'transform_target_method_param',
  'transform_target_param',
  'y',
  'y_test',
  'y_train'},
            Age       Fare  Pclass_1  Pclass_2  Pclass_3  Sex_male  SibSp_0  \
 448   5.000000  19.258301       0.0       0.0       1.0       0.0      0.0
 66   29.000000  10.500000       0.0       1.0       0.0       0.0      1.0
 52   49.000000  76.729202       1.0       0.0       0.0       0.0      0.0
 569  32.000000   7.854200       0.0       0.0       1.0       1.0      1.0
 699  42.000000   7.650000       0.0       0.0       1.0       1.0      1.0
 ..         ...        ...       ...       ...       ...       ...      ...
 60   22.000000   7.229200       0.0       0.0       1.0       1.0      1.0
 462  47.000000  38.500000       1.0       0.0       0.0       1.0      1.0
 453  49.000000  89.104202       1.0       0.0       0.0       1.0      0.0
 154  29.496336   7.312500       0.0       0.0       1.0       1.0      1.0
 533  29.496336  22.358299       0.0       0.0       1.0       0.0      1.0

      SibSp_1  SibSp_2  SibSp_3  ...  Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  \
 448      0.0      1.0      0.0  ...        0.0        0.0       0.0       0.0
 66       0.0      0.0      0.0  ...        1.0        0.0       0.0       0.0
 52       1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 569      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 699      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 ..       ...      ...      ...  ...        ...        ...       ...       ...
 60       0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 462      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 453      1.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 154      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0
 533      0.0      0.0      0.0  ...        0.0        0.0       0.0       0.0

      Cabin_T  Cabin_not_available  Embarked_C  Embarked_Q  Embarked_S  \
 448      0.0                  1.0         1.0         0.0         0.0
 66       0.0                  0.0         0.0         0.0         1.0
 52       0.0                  0.0         1.0         0.0         0.0
 569      0.0                  1.0         0.0         0.0         1.0
 699      0.0                  0.0         0.0         0.0         1.0
 ..       ...                  ...         ...         ...         ...
 60       0.0                  1.0         1.0         0.0         0.0
 462      0.0                  0.0         0.0         0.0         1.0
 453      0.0                  0.0         1.0         0.0         0.0
 154      0.0                  1.0         0.0         0.0         1.0
 533      0.0                  1.0         1.0         0.0         0.0

      Embarked_not_available
 448                     0.0
 66                      0.0
 52                      0.0
 569                     0.0
 699                     0.0
 ..                      ...
 60                      0.0
 462                     0.0
 453                     0.0
 154                     0.0
 533                     0.0

 [223 rows x 132 columns],
 448    1
 66     1
 52     1
 569    1
 699    0
       ..
 60     0
 462    0
 453    1
 154    0
 533    1
 Name: Survived, Length: 223, dtype: int64,
 5,
 None,
 True,
 [],
 [('Setup Config',
                                  Description             Value
   0                               session_id              7196
   1                                   Target          Survived
   2                              Target Type            Binary
   3                            Label Encoded              None
   4                            Original Data         (891, 12)
   5                           Missing Values              True
   6                         Numeric Features                 2
   7                     Categorical Features                 6
   8                         Ordinal Features             False
   9                High Cardinality Features             False
   10                 High Cardinality Method              None
   11                   Transformed Train Set        (668, 132)
   12                    Transformed Test Set        (223, 132)
   13                      Shuffle Train-Test              True
   14                     Stratify Train-Test             False
   15                          Fold Generator   StratifiedKFold
   16                             Fold Number                10
   17                                CPU Jobs                -1
   18                                 Use GPU              True
   19                          Log Experiment             False
   20                         Experiment Name  clf-default-name
   21                                     USI              79fa
   22                         Imputation Type            simple
   23          Iterative Imputation Iteration              None
   24                         Numeric Imputer              mean
   25      Iterative Imputation Numeric Model              None
   26                     Categorical Imputer          constant
   27  Iterative Imputation Categorical Model              None
   28           Unknown Categoricals Handling    least_frequent
   29                               Normalize             False
   30                        Normalize Method              None
   31                          Transformation             False
   32                   Transformation Method              None
   33                                     PCA             False

In [17]:
best_clf = pycc.compare_models()
tune_model = pycc.tune_model(best_clf, choose_better = True)
pycc.finalize_model(tune_model)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=7196, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
tune_model.predict_model("test.csv")

AttributeError: 'LogisticRegression' object has no attribute 'predict_model'